name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release
        run: echo "Triggering release"
  
  release:
    runs-on: ubuntu-latest
    needs: trigger-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npx semantic-release
